version: '3.9'
services:
  web:
    image: nginx
    volumes:
    - /home/az/develop/js-projects/vue-project/dist:/usr/share/nginx/html
    - ./config:/etc/nginx/conf.d
    ports:
    - "8888:80"
    environment:
    - NGINX_HOST=support.ru
    - NGINX_PORT=80
    restart: always
